#cloud-config
# vim: syntax=yaml
#

# Set your hostname here
hostname: e16dev
bootcmd:
  - [ ifup, wlan0 ]
  - [ bash, /etc/firstboot.d/10-resize-rootdisk ]

wifi:
  interfaces:
    wlan0:
      ssid: "The VPhone SE"
      password: "fjfjfjfj"
preserve_hostname: true
manage_etc_hosts: false
manage_resolv_conf: false
apt_preserve_sources_list: true

# You could modify this for your own user information
users:
  - name: e16
    primary-group: e16
    gecos: "E16 User"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,adm,dialout,audio,plugdev,netdev,video
    lock_passwd: true
    ssh-import-id: None
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDR2/jKggM+GlL0tzcb+GMSN3iGTjlG07iiAyOiF5c8hd71wJxjAjJJPptqRYlHgONmioBqgw3hC2Zb7ics34r6mw+luLVVkjDo+KE5DjCXUdVd9R2WJcaoFkEnIks8shFubYpFKD/8f9fLkC1Kg+PXXhNmnV4IfiCfm0+Vutra/RBuVJJMYN98o7+Z0Z84nhdUCCITxDHaFucCrjcCbs7r/+HxX81VDYvUMeh0wqqZL8gWgyUp+lNP4ugHxiAaXK66sWffqW0mUCJOtntVvqltHV1k+GbZZNeR39eCK0LJ1rqEtUxmK9PCAT4YSYGjNdlt54toOthwCuuxaGWuMaxH b8:27:eb:01:58:e1
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC4JF1iXi40giRC8e08NazNiggIeZSfXCBx+rI2V+L5bEwzymJyboJB2huMNZAQJNPTs+Mqd1HF+ku0YTuNQfMYfG1HQRGEBteyT4eaYsj4bveM+w6ocF2NywtdUXVutd3YuuQ610gXxMQIbJsd8UCpYhmlb/d/qUTq1xq2PrgZVmAK8pJke4EH30lI1HScoktHR3L/QzjQC8n3DDmmjpprN99fKwD6nY3u8+5WcPtiYbw9xxk0JdauU43p8nMJHtbli59ci5Vcgbfzu2o7SUn1/XCH1VWV7EYpimje5Tr8nB5zE8ltUKj44SfSyipBodlL5B5f4eGiMkU7W/bbHjoy0nZx1x4+I1BKWJaVdMfMe20lvEL057gwiX7g/555WJEwQLWN58+gterY4v1AXN/TUSqS59pxP+KhM8qTUcNKSceAa3HJpYqIStE0GI8iDEJ+SSrOW0ZwJWOUXembrx+oMj6PGCpZTxPwJNhbfsG8MUZ5bqaITWeQmD9FaJC1o/fEG3pRAdTajOSujDKbYQcHgw9P0mI5i5GT/udg8HA84OUXnW0MrHbLPhDikRdfgbYB2dUTyH62rfCRalrKwi6qZa2MWTAHIRFeCki58Y16yabMwUXCkzPAPNKu0X2yic1VT/qgqC5yVflcIF0JkqBcWnkK4lJFQ4MUvtmb86oL3w== jcollas@monolith.lan
resolv_conf:
  - nameservers: ['8.8.4.4', '8.8.8.8']
    options:
      rotate: true
      timeout: 1

# # Set the locale of the system
locale: "en_US.UTF-8"

# # Set the timezone
# # Value of 'timezone' must exist in /usr/share/zoneinfo
timezone: "America/New_York"

# # Update apt packages on first boot
package_update: false
package_upgrade: false
package_reboot_if_required: false


write_files:
  - content: |
      country=US
      ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
      update_config=1
      network={
        ssid="FiOS-JVHL0"
        psk="use7017cody470root"
        proto=RSN
        key_mgmt=WPA-PSK
        pairwise=CCMP TKIP
        group=CCMP TKIP
      }
      network={
        ssid="The VPhone SE"
        psk="fjfjfjfj"
      }
    path: /etc/wpa_supplicant/wpa_supplicant.conf
  - content: |
      allow-hotplug wlan0
      iface wlan0 inet dhcp
          wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
      iface default inet dhcp
    path: /etc/network/interfaces.d/wlan0
    permissions: '0644'
    owner: 'root:root'
  - content: |
      e16dev
    path: /etc/hostname
    permissions: '0644'
    owner: 'root:root'
  - content: |
      # Your system has configured 'manage_etc_hosts' as True.
      # As a result, if you wish for changes to this file to persist
      # then you will need to either
      # a.) make changes to the master file in /etc/cloud/templates/hosts.tmpl
      # b.) change or remove the value of 'manage_etc_hosts' in
      #     /etc/cloud/cloud.cfg or cloud-config from user-data
      #
      127.0.1.1 e16dev
      127.0.0.1 localhost
      
      # The following lines are desirable for IPv6 capable hosts
      ::1 ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts
      
    path: /etc/hosts
    permissions: '0644'
    owner: 'root:root'
  - content: |
      #!/bin/sh
      HOST_SN=`cat /proc/cpuinfo | grep Serial | cut -d ' ' -f 2 | sed s/^0*// |tr '[:lower:]' '[:upper:]'`
      DEC=`echo $((0x${HOST_SN}))`
      DEVICE_ID=`/sbin/ifconfig eth0 | /bin/grep ether | /usr/bin/awk '{print $2}'`
      HOST_NAME=`/bin/hostname`
      echo "$HOST_NAME","0x$HOST_SN","0d$DEC","$DEVICE_ID"
    path: /usr/local/bin/e16-info
    permissions: '0555'
    owner: 'root:root'
  - content: |
      ping_time=`/bin/ping -D -c 1 10.8.0.1 | grep ']' | cut -d ']' -f 1 | cut -d '[' -f 2 | cut -d '.' -f 1`
      if [ -z "$ping_time" ]; then
         exit
      fi
      /bin/echo $ping_time > /var/log/lastVpnCheck
    path: /usr/local/bin/e16-vpnping
    permissions: '0555'
    owner: 'root:root'
  - content: |
      #!/bin/bash
      # How many minutes to allow to pass before rebooting the machine?
      MAX_MINUTES_RESTART_VPN=60  #1 hours
      MAX_MINUTES_RESTART_PI=1440 #24 hours
      
      # How many minutes of warning (broadcast to logged in users) before actual reboot?
      MINUTES_OF_WARNING_BEFORE_REBOOT=2
      
      # Obtain the time when this script was last touched
      t_last_touch=`cat /var/log/lastVpnCheck`
      if [ $t_last_touch == "" ]; then
          t_last_touch=0
      fi
      
      t_now=`date +%s`
      
      # Calculate the difference in seconds between
      # the current time and the time of the last touch
      let t_diff_sec=$(( $t_now - $t_last_touch ))
      
      
      # Calculate the difference in minutes
      let t_diff_min=$(( $t_diff_sec / 60 ))
      
      # Display the elpased time
      echo Time elapsed since the last vpn contact: $t_diff_min minutes, $t_diff_sec seconds
      
      if (( $t_diff_min >= $MAX_MINUTES_RESTART_PI ))
      then
          echo $t_now > /var/log/lastSuccessfulVpnContact
          /sbin/shutdown -r +$MINUTES_OF_WARNING_BEFORE_REBOOT
      fi
      
      if (( $t_diff_min >= $MAX_MINUTES_RESTART_VPN ))
      then
          /bin/systemctl restart openvpn@client.service
      fi
    path: /usr/local/bin/e16-vpncheck
    permissions: '0555'
    owner: 'root:root'
  - content: |
      #!/bin/bash
      
      if [ -z "$1" ]; then
      #    echo Host name prefix required
          exit
      fi
      
      OLD_HOST=`cat /etc/hostname`
      HOST_SN=`cat /proc/cpuinfo | grep Serial | cut -d ' ' -f 2 | sed s/^0*// |tr '[:lower:]' '[:upper:]'`
      HOST_NAME=$1-$HOST_SN
      
      if [ "$OLD_HOST" != "$HOST_NAME" ]; then
          sed s/e16/$HOST_NAME/ /etc/hostname > /tmp/hostname
          sed s/e16/$HOST_NAME/g /etc/hosts > /tmp/hosts
          hostname $HOST_NAME
          cp /tmp/hostname /etc/hostname
          rm /tmp/hostname
          chown root.root /etc/hostname
          cp /tmp/hosts /etc/hosts
          rm /tmp/hosts
          chown root.root /etc/hosts
      #else
      #    echo Hostname correct
      fi
    path: /usr/local/bin/e16-setup
    permissions: '0555'
    owner: 'root:root'
  - content: |
      # DO NOT EDIT THIS FILE - edit the master and reinstall.
      # (/tmp/crontab.c0HMAQ/crontab installed on Sat Nov 24 14:34:39 2018)
      # (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
      # Edit this file to introduce tasks to be run by cron.
      # 
      # Each task to run has to be defined through a single line
      # indicating with different fields when the task will be run
      # and what command to run for the task
      # 
      # To define the time you can provide concrete values for
      # minute (m), hour (h), day of month (dom), month (mon),
      # and day of week (dow) or use '*' in these fields (for 'any').# 
      # Notice that tasks will be started based on the cron's system
      # daemon's notion of time and timezones.
      # 
      # Output of the crontab jobs (including errors) is sent through
      # email to the user the crontab file belongs to (unless redirected).
      # 
      # For example, you can run a backup of all your user accounts
      # at 5 a.m every week with:
      # 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
      # 
      # For more information see the manual pages of crontab(5) and cron(8)
      # 
      # m h  dom mon dow   command
      * * * * * /usr/local/bin/e16-vpnping
      */20 * * * * /usr/local/bin/e16-vpncheck
    path: /var/spool/cron/crontabs/root
    permissions: '0600'
    owner: 'root:crontab'
  - content: |
    path: /etc/openvpn/client.conf
  - content: |
      #!/bin/sh
      #/etc/init.d/e16
      ### BEGIN INIT INFO
      # Provides: e16
      # Required-Start:    $network $remote_fs $syslog ntp docker
      # Required-Stop:     $network $remote_fs $syslog ntp docker
      # Default-Start:     2 3 4 5
      # Default-Stop:
      # Short-Description: The E16 docker instances
      ### END INIT INFO
      set -e
      
      export PATH="${PATH:+$PATH:}/usr/sbin:/sbin:/usr/bin:/usr/local/bin"

      case "$1" in
          start)
          docker run --restart unless-stopped --detach --name watchtower -v /root/.docker/config.json:/config.json -v /var/run/docker.sock:/var/run/docker.sock v2tec/watchtower:armhf-latest  --cleanup
          ;;
          stop)
          docker stop watchtower
          docker rm watchtower
          ;;
          *)
          echo "Usage: /etc/init.d/e16 {start|stop}"
          exit 1
          ;;
      esac
      
      exit 0
    path: /etc/init.d/e16
    permissions: '0755'

# These commands will be run once on first boot only
runcmd:
  # Pickup the hostname changes
  - 'systemctl restart avahi-daemon'
  - 'ifup wlan0'

  # reset the hostname and make it stick
  - 'e16-setup e16dev'

  # updates
  - 'apt-get -y update'
  - 'apt-get -y upgrade'
  - 'apt-get -y install emacs25-nox openvpn ufw unattended-upgrades apt-listchanges build-essential pass zlib1g-dev'

  # remove the windowing system
  - 'apt-get autoremove -y'
  - 'apt-get autoclean -y'

  # write initial file for vpn check
  - 'date +%s > /var/log/lastVpnCheck'

  # Disable system async port login
  - 'systemctl stop getty@tty1.service'
  - 'systemctl disable getty@tty1.service'

  # disable bluetooth (except for us)
  - 'update-rc.d bluetooth remove'
  - '/etc/init.d/bluetooth stop'

  # start the vpn keep-up service
  - 'update-rc.d e16 defaults 98'
  - 'update-rc.d e16 enable'
  - '/etc/init.d/e16 start'
  
  # setup firewall
  - 'ufw allow ssh'
  - 'ufw allow 8080'
  - 'ufw allow in on docker0'
  - 'ufw allow out on docker0'
  - 'ufw allow out 443/udp'
  - 'ufw allow out 443/tcp'
  - 'ufw allow 53/udp'
  - 'ufw allow out 53/udp'
  - 'ufw allow 53/tcp'
  - 'ufw allow out 53/tcp'
  - 'ufw allow 123/udp'
  - 'ufw allow out 123/tcp'
  - 'ufw allow in to 224.0.0.0/4'
  - 'ufw allow in from 224.0.0.0/4'
  - 'ufw allow out to 224.0.0.0/4'
  - 'ufw allow out from 224.0.0.0/4'
  - 'ufw enable'

  # start the vpn
  - 'systemctl enable openvpn@client.service'
  - 'systemctl start openvpn@client.service'
  
